---
services:
  nautobot:
    command: "nautobot-server runserver 127.0.0.1:8080"
    ports:
      - "8080:8080"
    volumes:
      - "../config/nautobot_config.py:/opt/nautobot/nautobot_config.py"
      - "../jobs:/opt/nautobot/jobs"
    healthcheck:
      interval: "30s"
      timeout: "10s"
      start_period: "60s"
      retries: 3
      test: ["CMD", "true"]  # Due to layering, disable: true won't work. Instead, change the test
  celery_worker:
    volumes:
      - "../config/nautobot_config.py:/opt/nautobot/nautobot_config.py"
      - "../jobs:/opt/nautobot/jobs"
  nginx:
    ports:
      - "443:443"
    volumes:
      - "../environments/nautobot.key:/etc/ssl/private/nautobot.key"
      - "../environments/nautobot.crt:/etc/ssl/certs/nautobot.crt"
      - "../config/nautobot.conf:/etc/nginx/sites-available/nautobot.conf"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail https://localhost || exit 1"]
      interval: 30s       # Time between running the check (default 30s)
      timeout: 5s         # Time before considering the check failed
      retries: 3          # How many times to retry before marking as unhealthy
      start_period: 10s   # Start period before running first healthcheck